name: Martin Cheung
job_title: Data Scientist
logo: "/images/profile_pic.jpeg?raw=true"

description:
  <p align="center">
  <b><a href="https://www.linkedin.com/in/martin-cheung-ds"/>LinkedIn</a></b> |
  <b><a href="https://github.com/martycheung">GitHub</a></b>
  </p>
  
  <p align="justify">
  Currently Data Scientist at <a href="https://www.relayr.io">relayr</a> base in Munich, building predictive maintenance and anomaly detection systems for industrial clients.
  <br><br>
  Previously Data Scientist at <a href="https://www.accenture.com">Accenture</a> in Australia for 4 years, with experience in delivering varied data science projects in many industries such as Telco, Banking and Oil & Gas.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-168653700-1 # your Google Analytics tracking ID here
