title: Martin Cheung
logo: "/images/profile_pic.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, currently at relayr, building predictive maintenance and anomaly detection systems to help industrial clients stay relevant.
  <br><br>
  Previously at Accenture, with experience in delivering varied data science projects in many industries such as Telco, Banking, Resources and Sport.
  <br><br>
  <a href="https://www.linkedin.com/in/martin-cheung-ds/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-168653700-1 # your Google Analytics tracking ID here
