name: <p align="center">Martin Cheung</p>
job_title: <p align="center">Data Scientist</p>
logo: "/images/profile_pic.jpeg?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/martin-cheung-ds"/>LinkedIn</a> |
  <a href="https://github.com/martycheung">GitHub</a>
  </p>
  
  <p align="justify">
  Currently Data Scientist at <a href="relayr.io">relayr</a>, building predictive maintenance and anomaly detection systems for industrial clients.
  <br><br>
  Previously worked at Accenture for 4 years, with experience in delivering varied data science projects in many industries such as Telco, Banking and Oil & Gas.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-168653700-1 # your Google Analytics tracking ID here
